name: "Terraform Format"
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  terraform_format_test:
    uses: ./.github/workflows/terraformformat.yml
