name: "Terraform All Branches"
on:
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"
  push:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  terraform-format-test:
    uses: ./.github/workflows/terraform_format.yml
  tfsec-pr-commenter:
    uses: ./.github/workflows/tfsec_pr_commenter.yml
  terraform-docs:
    uses: ./.github/workflows/documentation.yml
